services:
  # The Database
  exam-db:
    image: postgres:15-alpine
    container_name: exam-db
    environment:
      POSTGRES_USER: examadmin
      POSTGRES_PASSWORD: examadmin
      POSTGRES_DB: examdb
    ports:
      - "5433:5432"

  # The Java Backend
  backend:
    # POINT TO THE NESTED FOLDER
    build: ./ExamBackend/ExamBackend 
    container_name: exam-backend
    env_file:
      - ./ExamBackend/ExamBackend/.env
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:postgresql://exam-db:5432/examdb
    depends_on:
      - exam-db

  # The React Frontend
  frontend:
    build: ./ExamFrontend
    container_name: exam-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
